print("Band Name Generator")
print("-------------------")
city = input("What is the name of the city you grew up in? \n")
pet = input("What is your pet's name? \n")
print(f"Your band name shoud be {city.title()} & {pet.title()}.")